# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: communicate.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63ommunicate.proto\"\x88\x03\n\x11\x43lientGrpcMessage\x12<\n\x0fsend_parameters\x18\x01 \x01(\x0b\x32!.ClientGrpcMessage.SendParametersH\x00\x12;\n\x0fget_new_version\x18\x02 \x01(\x0b\x32 .ClientGrpcMessage.GetNewVersionH\x00\x1a\xc9\x01\n\x0eSendParameters\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x1c\n\x14train_dataset_length\x18\x02 \x01(\x03\x12O\n\x10new_model_weight\x18\x03 \x03(\x0b\x32\x35.ClientGrpcMessage.SendParameters.NewModelWeightEntry\x1a\x35\n\x13NewModelWeightEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c:\x02\x38\x01\x1a%\n\rGetNewVersion\x12\x14\n\x0cversion_path\x18\x01 \x01(\tB\x05\n\x03msg\"/\n\x0eTransferStatus\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2E\n\x0fWeightsTransfer\x12\x32\n\x0bSendWeights\x12\x12.ClientGrpcMessage\x1a\x0f.TransferStatusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'communicate_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLIENTGRPCMESSAGE_SENDPARAMETERS_NEWMODELWEIGHTENTRY']._loaded_options = None
  _globals['_CLIENTGRPCMESSAGE_SENDPARAMETERS_NEWMODELWEIGHTENTRY']._serialized_options = b'8\001'
  _globals['_CLIENTGRPCMESSAGE']._serialized_start=22
  _globals['_CLIENTGRPCMESSAGE']._serialized_end=414
  _globals['_CLIENTGRPCMESSAGE_SENDPARAMETERS']._serialized_start=167
  _globals['_CLIENTGRPCMESSAGE_SENDPARAMETERS']._serialized_end=368
  _globals['_CLIENTGRPCMESSAGE_SENDPARAMETERS_NEWMODELWEIGHTENTRY']._serialized_start=315
  _globals['_CLIENTGRPCMESSAGE_SENDPARAMETERS_NEWMODELWEIGHTENTRY']._serialized_end=368
  _globals['_CLIENTGRPCMESSAGE_GETNEWVERSION']._serialized_start=370
  _globals['_CLIENTGRPCMESSAGE_GETNEWVERSION']._serialized_end=407
  _globals['_TRANSFERSTATUS']._serialized_start=416
  _globals['_TRANSFERSTATUS']._serialized_end=463
  _globals['_WEIGHTSTRANSFER']._serialized_start=465
  _globals['_WEIGHTSTRANSFER']._serialized_end=534
# @@protoc_insertion_point(module_scope)
